sudo: required

# blocklist
branches:
  except:
  - master

# safelist
branches:
  only:
  - ci

notifications:
  email:
    on_success: never # default: change
    on_failure: change # default: always

services:
  - docker

before_install:
- docker pull dranoel/cbs-devel

script:
# - ls -al ${PWD}
- docker run --rm --workdir=/workspace --volume ${PWD}:/workspace dranoel/cbs-devel:latest ./build.sh