version: 1.1.0-{build}

branches:
  only:
    - master

pull_requests:
  do_not_increment_build_number: true

image: Visual Studio 2017

environment:
  CleanFolder: ../Source/Example/Web/bin
  SolutionFolder: ../Source/Example/Example.sln

only_commits:
  files:
    - Source/Example/

build_script:
- ps: ./Build/build.ps1