apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress  
  annotations:    
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/rewrite-target: /
spec:  
  rules:
  - host: test.cbsrc.org
    http:
      paths:      
      - path: {services.usermanagement.path}
        backend:
          serviceName: {services.usermanagement.name}
          servicePort: 80
      - path: {services.volunteerreporting.path}
        backend:
          serviceName: {services.volunteerreporting.name}
          servicePort: 80
      - path: {services.admin.path}
        backend:
          serviceName: {services.admin.name}
          servicePort: 80