version: '3'
services:
  cbs-volunteerreporting-db:
    image: mongo
    ports:
        - "27017:27017"

  cbs-volunteerreporting-backend:
    image: karolikl/cbs-vr-backend:latest
    links:
        - cbs-volunteerreporting-db
    depends_on:
        - cbs-volunteerreporting-db
    ports:
        - "8080:80"